---
  - name: Play for Install Nginx on WebServers
    hosts: localhost
    gather_facts: yes
    vars:
      custom_heading: "Welcome To AWS & DevOps World!!!"
      todays_date: "{{ ansible_facts['date_time']['date'] }}"
      host_name: "{{ ansible_facts['hostname'] }}"
      fqdn_name: "{{ ansible_facts['fqdn'] }}"
      ip_address: "{{ ansible_facts['eth0']['ipv4']['address'] }}"
    tasks:
       - name: Run yum Update
         shell: yum update && yum install -y python3
         
       - name: Install Nginx Server
         yum: >
           name=nginx
           state=present
       - name: Copy the files to index destination folder.
         template: >
            src=/myrepo/index.j2
            dest=/usr/share/nginx/html/index.html
            owner=root
            group=root
            mode=0644
       - name: Copy the style files to destination folder.
         copy: >
            src=/myrepo/style.css
            dest=/usr/share/nginx/html/style.css
            owner=root
            group=root
            mode=0644
       - name: Copy the javascript files to destination folder.
         copy: >
            src=/myrepo/scorekeeper.js
            dest=/usr/share/nginx/html/scorekeeper.js
            owner=root
            group=root
            mode=0644
       - name: restart nginx
         command: systemctl restart nginx
